### ISSUE TITLE
Production error

### ISSUE THREAD

**Issue by esseifforte** [tomik23/webpack-boilerplate#12]
Hi,
in npm run prod:
[webpack-cli] ValidationError: Invalid options object. Terser Plugin has been initialized using an options object that does not match the API schema.
 - options has an unknown property 'sourceMap'. These properties are valid:
   object { test?, include?, exclude?, parallel?, minify?, terserOptions?, extractComments? }

thanks

**Comment by tomik23** [comment]
For me, this problem does not occur and should not occur. As you look at the documentation, the Terser plugin has an option like the [sourceMap](https://webpack.js.org/plugins/terser-webpack-plugin/#sourcemap). Try removing `node_modules` and reinstalling all dependencies. For me, this problem does not occur, I tested by running it through yarn or npm.

**Comment by esseifforte** [comment]
thank you
