### ISSUE TITLE
unable to resolve dependency tree

### ISSUE THREAD

**Issue by Khwarazmi** [tomik23/webpack-boilerplate#14]
`npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! Found: pug@3.0.0
npm ERR! node_modules/pug
npm ERR!   dev pug@"^3.0.0" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! dev pug-loader@"^2.4.0" from the root project
npm ERR!
npm ERR! Conflicting peer dependency: pug@2.0.4
npm ERR! node_modules/pug
npm ERR!   peer pug@"^2.0.0" from pug-loader@2.4.0
npm ERR!   node_modules/pug-loader
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR! See /home/khwabuntu/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/khwabuntu/.npm/_logs/2021-01-16T02_03_26_371Z-debug.log`

**Comment by tomik23** [comment]
Hi,
Unfortunately, I have no idea what's wrong. You may try removing node_modules and reinstalling the dependencies. I work under windows and this problem does not occur for me.
