### ISSUE TITLE
loading fonts

### ISSUE THREAD

**Issue by one618** [tomik23/webpack-boilerplate#15]
Hello,
can you guide me throw on how to load fonts ?
like if i have a folder called fonts and inside it a font
how can i load it and copy it to production folder ?

**Comment by tomik23** [comment]
Hi,
Take a look at this, on production you can copy the entire folder the same as in this example -> [copy-webpack-plugin](https://github.com/tomik23/webpack-boilerplate/blob/master/config/webpack.prod.js#L80)
